ALTER TABLE dw.fact_weather_hourly
  ADD COLUMN IF NOT EXISTS humidity_pct DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS pressure_hpa DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS visibility_m DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS uv_index DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS precip_probability_pct DOUBLE PRECISION;